In [14]:
from pandas import read_csv
from sklearn.ensemble import RandomForestRegressor
import numpy as np

In [6]:
# load data after ETL level
data = read_csv("../data/preprocessed/sales_train_preprocessed.csv")
# data = read_csv("../data/preprocessed/sales_train_preprocessed_long.csv")
data.head(3)

,date_block_num,shop_id,item_id,item_cnt_month,item_category_id,month,shop_city_encoded,shop_type_encoded,sub_category_encoded,item_price_lag_1,...,item_shop_cnt_month_lag_mean_1_3,ratio_item_shop_cnt_month_lag_mean_1_3_to_lag1,sub-category_shop_cnt_month_lag_mean_1_3,ratio_sub-category_shop_cnt_month_lag_mean_1_3_to_lag1,sub-category_item_cnt_month_lag_mean_1_3,ratio_sub-category_item_cnt_month_lag_mean_1_3_to_lag1,item_shop-type_cnt_month_lag_mean_1_3,ratio_item_shop-type_cnt_month_lag_mean_1_3_to_lag1,item_shop-city_cnt_month_lag_mean_1_3,ratio_item_shop-city_cnt_month_lag_mean_1_3_to_lag1
0,0,0,27,1.0,19,1,1,6,5,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,33,1.0,37,1,1,6,11,0.0,...,0.0,0.0,0.666667,666666.666667,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,317,1.0,45,1,1,6,12,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
len(data)

1320229

In [8]:
model = RandomForestRegressor(
        n_estimators=150,
        max_depth=10,
        max_features="log2",
        min_samples_split=40,
        verbose=5,
        oob_score=True
    )

In [9]:
X_train = data.drop(columns=['item_cnt_month', 'date_block_num'])
y_train = data[['item_cnt_month']]

In [10]:
model.fit(X_train, y_train['item_cnt_month'].to_list())

building tree 1 of 150
building tree 2 of 150
building tree 3 of 150
building tree 4 of 150
building tree 5 of 150
building tree 6 of 150
building tree 7 of 150
building tree 8 of 150
building tree 9 of 150
building tree 10 of 150
building tree 11 of 150
building tree 12 of 150
building tree 13 of 150
building tree 14 of 150
building tree 15 of 150
building tree 16 of 150
building tree 17 of 150

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:   48.3s

building tree 18 of 150
building tree 19 of 150
building tree 20 of 150
building tree 21 of 150
building tree 22 of 150
building tree 23 of 150
building tree 24 of 150
building tree 25 of 150
building tree 26 of 150
building tree 27 of 150
building tree 28 of 150
building tree 29 of 150
building tree 30 of 150
building tree 31 of 150
building tree 32 of 150
building tree 33 of 150
building tree 34 of 150
building tree 35 of 150
building tree 36 of 150
building tree 37 of 150
building tree 38 of 150
building tree 39 of 150
building tree 40 of 150
building tree 41 of 150
building tree 42 of 150
building tree 43 of 150
building tree 44 of 150
building tree 45 of 150
building tree 46 of 150
building tree 47 of 150
building tree 48 of 150
building tree 49 of 150
building tree 50 of 150
building tree 51 of 150
building tree 52 of 150
building tree 53 of 150
building tree 54 of 150
building tree 55 of 150
building tree 56 of 150
building tree 57 of 150
building tree 58 of 150
building tree 59 of 150
building tree 60 of 150
building tree 61 of 150
building tree 62 of 150
building tree 63 of 150
building tree 64 of 150
building tree 65 of 150
building tree 66 of 150
building tree 67 of 150
building tree 68 of 150
building tree 69 of 150
building tree 70 of 150
building tree 71 of 150

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:  3.4min

building tree 72 of 150
building tree 73 of 150
building tree 74 of 150
building tree 75 of 150
building tree 76 of 150
building tree 77 of 150
building tree 78 of 150
building tree 79 of 150
building tree 80 of 150
building tree 81 of 150
building tree 82 of 150
building tree 83 of 150
building tree 84 of 150
building tree 85 of 150
building tree 86 of 150
building tree 87 of 150
building tree 88 of 150
building tree 89 of 150
building tree 90 of 150
building tree 91 of 150
building tree 92 of 150
building tree 93 of 150
building tree 94 of 150
building tree 95 of 150
building tree 96 of 150
building tree 97 of 150
building tree 98 of 150
building tree 99 of 150
building tree 100 of 150
building tree 101 of 150
building tree 102 of 150
building tree 103 of 150
building tree 104 of 150
building tree 105 of 150
building tree 106 of 150
building tree 107 of 150
building tree 108 of 150
building tree 109 of 150
building tree 110 of 150
building tree 111 of 150
building tree 112 of 150
building tree 113 of 150
building tree 114 of 150
building tree 115 of 150
building tree 116 of 150
building tree 117 of 150
building tree 118 of 150
building tree 119 of 150
building tree 120 of 150
building tree 121 of 150
building tree 122 of 150
building tree 123 of 150
building tree 124 of 150
building tree 125 of 150
building tree 126 of 150
building tree 127 of 150
building tree 128 of 150
building tree 129 of 150
building tree 130 of 150
building tree 131 of 150
building tree 132 of 150
building tree 133 of 150
building tree 134 of 150
building tree 135 of 150
building tree 136 of 150
building tree 137 of 150
building tree 138 of 150
building tree 139 of 150
building tree 140 of 150
building tree 141 of 150
building tree 142 of 150
building tree 143 of 150
building tree 144 of 150
building tree 145 of 150
building tree 146 of 150
building tree 147 of 150
building tree 148 of 150
building tree 149 of 150
building tree 150 of 150

[Parallel(n_jobs=1)]: Done 150 out of 150 | elapsed:  7.1min finished

RandomForestRegressor(max_depth=10, max_features='log2', min_samples_split=40,
                      n_estimators=150, oob_score=True, verbose=5)

In [11]:
# load test data
data_test = read_csv("../data/preprocessed/test_preprocessed.csv")
data_test.head(3)

,shop_id,item_id,item_category_id,month,ID,shop_city_encoded,shop_type_encoded,sub_category_encoded,item_price_lag_1,category_price_lag_1,...,item_shop_cnt_month_lag_mean_1_3,ratio_item_shop_cnt_month_lag_mean_1_3_to_lag1,sub-category_shop_cnt_month_lag_mean_1_3,ratio_sub-category_shop_cnt_month_lag_mean_1_3_to_lag1,sub-category_item_cnt_month_lag_mean_1_3,ratio_sub-category_item_cnt_month_lag_mean_1_3_to_lag1,item_shop-type_cnt_month_lag_mean_1_3,ratio_item_shop-type_cnt_month_lag_mean_1_3_to_lag1,item_shop-city_cnt_month_lag_mean_1_3,ratio_item_shop-city_cnt_month_lag_mean_1_3_to_lag1
0,3,5037,19,11,0,4,5,5,1499.0,1537.237267,...,1.666667,1.666665,1.666667,1.666665e+00,1.666667,1.666665,1.666667,1.666665,1.666667,1.666665
1,3,5320,55,11,1,4,5,13,0.0,327.477705,...,0.000000,0.000000,1.666667,1.666667e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,3,5233,19,11,2,4,5,5,1199.0,1537.237267,...,1.666667,1.666665,1.666667,1.666665e+00,1.666667,1.666665,1.666667,1.666665,1.666667,1.666665

In [15]:
answer = data_test[['ID']]
answer['ID'] = answer['ID'].astype(int)
answer['item_cnt_month'] = model.predict(data_test.drop(columns='ID'))
# answer['item_cnt_month'] = model.predict(data_test_for_model.drop(columns='ID'))
# answer['item_cnt_month'] = answer['item_cnt_month'].apply(lambda x: x if x != 0 else 1)
# target postprocessing
answer['item_cnt_month'] = np.floor(answer['item_cnt_month'])
answer

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.9s
[Parallel(n_jobs=1)]: Done 150 out of 150 | elapsed:    3.8s finished

            ID  item_cnt_month
0            0             1.0
1            1             1.0
2            2             1.0
3            3             1.0
4            4             2.0
...        ...             ...
214195  214195             1.0
214196  214196             1.0
214197  214197             1.0
214198  214198             1.0
214199  214199             1.0

[214200 rows x 2 columns]

In [17]:
answer.to_csv("../data/preprocessed/sales_test_answer.csv", index=False)